description: "Get last release"
inputs:
  repo:
    description: 'repository name'
    required: true
  token:
    description: 'token name'
    required: true
outputs:
  release_version:
    description: 'target repo latest release'
runs:
  using: "composite"
  steps:
    - name: get_release
      id: get_release
      shell: bash
      run: |
        RELEASE_VERSION=`curl -sL --no-progress-bar \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ inputs.repo }}/releases/latest" | jq .tarball_url`
        echo "release_version=${RELEASE_VERSION}" >> $GITHUB_ENV
        echo "release_version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
