name: Check parent release
on:
  workflow_dispatch:

jobs:
  release_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: getter
        id: getter
        uses: ./.github/actions/get-release
        with:
          token: ${{ github.token }}
          repo: brechtsanders/winlibs_mingw
      - name: printer
        run: |
          echo "release_version: ${{ steps.getter.outputs.release_version }}"
