name: Check parent release
on:
  workflow_dispatch:

jobs:
  release_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: getter
        id: getter
        uses: ./.github/actions/get-release
        with:
          token: ${{ github.token }}
          repo: brechtsanders/winlibs_mingw
        env:
          RELEASE_VERSION: ${{ steps.getter.outputs.release_version }}
      - name: printer
        run: |
          echo "release_version: ${{ steps.getter.outputs.release_version }}"
          echo "release_version: ${{ env.RELEASE_VERSION }}"
          echo "release_version: ${{ env.release_version }}"
